### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by DerGut** [codeforosnabrueck/codeforosnabrueck.github.io#6]
Add a small image that is shown in the address bar, bookmarks list etc.
![screen shot 2018-01-31 at 23 58 26](https://user-images.githubusercontent.com/12832754/35652200-e9dd7400-06e2-11e8-90ca-0674eb9b30bb.png)

**Comment by JarnoRFB** [comment]
done by  06fb0d79c884d35ec08fd43cb6d21ad2f4ee2e54
